### ISSUE TITLE
IPN not recieving

### ISSUE THREAD

**Issue by joedarsh** [andyplak/events-manager-pro-paypal-chained-payments#7]
Just started using this, and I'm having IPN issues - I can see on PayPal that some are sending, and some are retrying, but on EM all bookings are showing as 'Awaiting PayPal payment' - on my IPN options on PayPal, I can't enable IPN without giving it a return URL - on the PayPal gateway packaged with EM Pro, it gives you a return URL to use - what should I be putting in to make this work with this gateway?

Massive thanks for building this and making it available by the way!

**Comment by andyplak** [comment]
@joedarsh The IPN setup for Adaptive Payments is far from intuitive. I seem to have the same issue every time someone sets up this plugin (clearly docs need improving). Because the PayPal request is setup via the Adaptive Payments API, the IPN notification url is set at the time the booking is made and therefore there is no need to tell paypal in the admin section where to send them (this differs from the packaged PayPal gateway in Events Manager). It is, however, essential that the IPN setting in PayPal are correct. From memory, I think they need on / enabled, but message delivery off:

![pp-ipn-settings](https://cloud.githubusercontent.com/assets/540165/17537065/e4bf4f86-5e99-11e6-968f-90aef5e5c580.png)

To be able to enable them, you need to add a valid url, which can be anything (it doesn't matter), because you'll then disable the messages.

With that set correctly, if it still doesn't work, the next thing to do is verify that the IPN messages are reaching your server. If you are testing on localhost this will inevitably not work, likewise firewalls could cause you problems. Take a look at the web server (apache) access logs to see if you can see them coming in.

**Comment by joedarsh** [comment]
Thanks for replying so quickly!

I've tried it with all possible variations of IPN settings (I did have messages enabled to start with, but disabled them and still no joy) - I can't access my Apache logs as annoyingly, One.com keeps them well hidden - I'm waiting on a support ticket from them to gain access.

Looking at my IPN history, when the messages are enabled, I can see that they are getting a 403 response. When I first tested this with the adaptive payments, it all worked fine, but when the site went live to sales a couple of days ago, the IPN stopped coming through (I actually had the IPN messages enabled when it was working for testing as well).

There's another PayPal parameter - Payment Data Transfer - does this have any implications for this plugin?

Thanks again for the support, very much appreciated!

**Comment by andyplak** [comment]
Just refreshing my memory on this one. The plugin adds a rewrite url, so its worth checking that that works:

https://github.com/andyplak/events-manager-pro-paypal-chained-payments/blob/master/events-manager-pro-pp-chained-payments.php#L28-L33

What do you get when you got to yoursiteurl/pp-chained-ipn ?

You should get this message:

_"Error: Missing POST variables. Identification is not possible. If you are not PayPal and are visiting this page directly in your browser, this error does not indicate a problem, but simply means EM is correctly set up and ready to receive IPNs from PayPal only."_

If not, then something is wrong with the url rewrite.

Also, can you check which URL does PayPal report the IPN was sent to for those that get the 403 response?

**Comment by joedarsh** [comment]
Still waiting on my Apache logs...

That URL does give that message, and when PayPal gives the 403 error, the URL it's sending to is mysite/pp-chained-ipn. This is only when messages are turned on though - if they're turned off, the IPN history just shows 'disabled' and you can't see any errors or information.

**Comment by joedarsh** [comment]
Hi Andy

I'd like to apologise for wasting your time - after spending hours researching and doing loads of trial and error, I had the sudden realisation that I had a plugin (IQ country block) blocking all back-end access apart from from the UK - and PayPal IPN responses come from the USA. Disabled it, and it worked instantly... Embarrassing facepalm here!

So apologies again, thank you for the support, and thank you for making this plugin!

**Comment by andyplak** [comment]
@joedarsh No problem. I failed to ask the first most basic question: 

"have you tested with all other plugins disabled and with a default WP theme?"

I could have saved us both some time there. Because IPN settings can be so problematic I went down that route first instead.
